{{- $root := . -}}
{{- $appName := include "herokucito-app.fullname" . -}}
{{- range $serviceName, $service := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}-{{ $serviceName }}
  labels:
    {{- include "herokucito-app.serviceLabels" (dict "root" $root "serviceName" $serviceName) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "herokucito-app.serviceSelectorLabels" (dict "root" $root "serviceName" $serviceName) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "herokucito-app.serviceLabels" (dict "root" $root "serviceName" $serviceName) | nindent 8 }}
        app.kubernetes.io/component: server
    spec:
      serviceAccountName: {{ include "herokucito-app.serviceAccountName" $root }}
      containers:
        - name: {{ $serviceName }}
          image: {{ include "herokucito-app.image" (dict "service" $service "serviceName" $serviceName) | quote }}
          {{- if $service.command }}
          command:
            {{- toYaml $service.command | nindent 12 }}
          {{- end }}
          {{- if $service.port }}
          ports:
            - name: http
              containerPort: {{ $service.port }}
              protocol: TCP
          {{- end }}
          {{- include "herokucito-app.env" (dict "root" $root "serviceName" $serviceName "service" $service) | nindent 10 }}
          resources:
            {{- include "herokucito-app.resources" (dict "root" $root "preset" $service.resources) | nindent 12 }}
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
          {{- if $service.port }}
          livenessProbe:
            httpGet:
              path: {{ dig "health" "path" "/" $service }}
              port: http
            timeoutSeconds: 4
            failureThreshold: 3
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: {{ dig "health" "path" "/" $service }}
              port: http
            timeoutSeconds: 5
            periodSeconds: 1
          {{- end }}
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 100Mi
{{- end }}
