apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "herokucito-web.serviceAccountName" . }}
  labels:
    {{- include "herokucito-web.labels" . | nindent 4 }}
automountServiceAccountToken: false
