apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "herokucito-app.serviceAccountName" . }}
  labels:
    {{- include "herokucito-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
automountServiceAccountToken: false
