---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "{{ .Values.project }}"
  namespace: argocd
spec:
  description: Project deployed with Herokucito
  sourceRepos:
    - https://github.com/ludat/herokucito.git
    - ghcr.io/ludat/charts
    - "{{ include "herokucito-project.repoUrl" . }}"
  sourceNamespaces:
    - {{ .Values.project | quote }}
  destinations:
    - namespace: {{ .Values.project | quote }}
      server: https://kubernetes.default.svc
