image:
  repository: null
  tag: null

preCommand: null

postCommand: null

expose:
  enabled: false
  host: null

secrets: []

port: 8000

postgres:
  enabled: false
  uriEnv: DATABASE_URL
  ha: false
  backups: false
  failsafe: false
