name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    strategy:
      matrix:
        chart:
          - herokucito-web
          - herokucito-review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieve version from Chart.yaml
        id: chart_version
        run: |
          echo "version=$(yq '.version' charts/${{ matrix.chart }}/Chart.yaml)" >> "$GITHUB_OUTPUT"

      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login -u ${{ github.actor }} --password-stdin ghcr.io

      - name: Push Chart to GHCR (${{ steps.chart_version.outputs.version }})
        run: |
          set -euo pipefail
          set -x
          if helm pull oci://ghcr.io/ludat/charts/${{ matrix.chart }} --version ${{ steps.chart_version.outputs.version }}; then
            echo "Version ${{ steps.chart_version.outputs.version }} exists."
            echo "Failing."
            exit 1
          fi

          helm package charts/${{ matrix.chart }}

          helm push "${{ matrix.chart }}-${{ steps.chart_version.outputs.version }}.tgz" oci://ghcr.io/ludat/charts
